import { NextRequest, NextResponse } from "next/server"
import speakeasy from "speakeasy"

// TOTP secrets for each admin account - Valid base32 encoded secrets generated by speakeasy
const ADMIN_SECRETS: Record<string, string> = {
  "montyflowchain890@gmail.com": "NERVMVKEI5BWYPZ2MFPHS3BROA7EERJ7MZESSYREJFYUAYR6OEYA",
  "bitcoin890@gmail.com": "IJJDO3DQLBLFATKQIZVSGN3TKREXWZ3XNVQTUOBROI4XG52SIQ7A",
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { email } = body

    const adminEmail = (email ?? "montyflowchain890@gmail.com").toLowerCase().trim()

    // Check if this is a valid admin email
    if (!ADMIN_SECRETS[adminEmail]) {
      return NextResponse.json(
        { success: false, error: "Admin account not found" },
        { status: 404 }
      )
    }

    const secret = ADMIN_SECRETS[adminEmail]

    return NextResponse.json({
      success: true,
      setupKey: secret,
      qrLabel: `FlowChain Admin (${adminEmail})`,
      issuer: "FlowChain Admin",
      instructions: `1. Open Google Authenticator app\n2. Tap + to add a new account\n3. Select "Enter a setup key"\n4. Enter or scan this key: ${secret}\n5. The app will generate 6-digit codes\n6. Enter the code during login for 2FA`,
    })
  } catch (error) {
    console.error("Error generating TOTP setup:", error)
    return NextResponse.json(
      { success: false, error: "Failed to generate setup key" },
      { status: 500 }
    )
  }
}
